# Generated by Django 4.2.30 on 2026-06-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='frames/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('orientation', models.CharField(choices=[('VERTICAL', 'Vertical'), ('HORIZONTAL', 'Horizontal')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='frames.frame')),
            ],
        ),
    ]
