# Generated by Django 4.2.30 on 2026-06-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framevariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frame_variants/'),
        ),
    ]
