# Generated by Django 4.2.30 on 2026-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_framevariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='framevariant',
            name='thickness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
