# Generated by Django 4.2.30 on 2026-06-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frames', '0003_framevariant_thickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='customer_uploads/')),
                ('status', models.CharField(choices=[('TEMP', 'Temporary'), ('FINAL', 'Final')], default='TEMP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frames.framevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
