# Generated by Django 4.2.30 on 2026-06-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_customerupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='framevariant',
            name='photo_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='photo_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='photo_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='photo_width',
            field=models.IntegerField(default=0),
        ),
    ]
