# Generated by Django 4.2.30 on 2026-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_framevariant_photo_height_framevariant_photo_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerupload',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerupload',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerupload',
            name='zoom_level',
            field=models.FloatField(default=1.0),
        ),
    ]
